name: ci

on:
  push:
    branches:
      - 'master'
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # <repo>
  IMAGE_NAME: ${{ github.event.repository.name }}
  TEST_TAG: user/app:test
  LATEST_TAG: user/app:latest
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package dockerfile:build -DskipTests

      - name: Build Image
        run: |
          docker build -t civic881027/database -f docker/Dockerfile .
          docker build -t civic881027/simpleshopapp -f Dockerfile .
      - name: Push Image
        run: |
          docker push civic881027/database
          docker push civic881027/simpleshopapp

        
          

